hexbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10  

  # Position Controllers ---------------------------------------

  thigh_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: thigh_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  thigh_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: thigh_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  thigh_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: thigh_3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  thigh_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: thigh_4_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  thigh_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: thigh_5_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  thigh_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: thigh_6_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  shin_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: shin_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  shin_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: shin_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  shin_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: shin_3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  shin_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: shin_4_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  shin_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: shin_5_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  shin_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: shin_6_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  foot_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: foot_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  foot_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: foot_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  foot_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: foot_3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  foot_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: foot_4_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  foot_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: foot_5_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  foot_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: foot_6_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
